# Generated by Django 4.2 on 2026-03-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_isbn_fine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fine',
            options={'verbose_name': 'Штраф', 'verbose_name_plural': 'Штрафы'},
        ),
        migrations.AlterField(
            model_name='fine',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Не оплачен'), ('paid', 'Оплачен')], default='unpaid', max_length=20, verbose_name='Статус'),
        ),
    ]
