# Generated by Django 4.2 on 2026-04-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_fine_options_alter_fine_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.FileField(blank=True, null=True, upload_to='books/', verbose_name='Файл книги (PDF)'),
        ),
    ]
