# Generated by Django 4.2 on 2026-04-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_book_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_file',
        ),
        migrations.AddField(
            model_name='book',
            name='yandex_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Яндекс.Диск'),
        ),
    ]
