# Generated by Django 4.2 on 2026-04-14 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_avg_rating_book_reviews_count_review'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
